import:
 - ~/.config/alacritty/themes/themes/base16_default_dark.yaml

font:
  size: 14
  normal:
    family: SFMono Nerd Font Mono
    style: Regular
  bold:
    family: SFMono Nerd Font Mono
    style: Bold
  italic:
    family: SFMono Nerd Font Mono
    style: Bold
    style: Italic

